import type { EstiloBaile, PoseReferencia } from "@/types/practica";

// Índices MediaPipe Pose Landmarker
// 0=nariz, 11=hombro_izq, 12=hombro_der, 13=codo_izq, 14=codo_der
// 15=muñeca_izq, 16=muñeca_der, 23=cadera_izq, 24=cadera_der
// 25=rodilla_izq, 26=rodilla_der, 27=tobillo_izq, 28=tobillo_der

export const POSES_REFERENCIA: Record<EstiloBaile, PoseReferencia[]> = {
  bachata: [
    {
      nombre: "Paso básico bachata",
      descripcion: "Paso lateral con cadera, brazos a los lados del cuerpo",
      keypoints: {
        hombro_izq: { x: 0.35, y: 0.3 },
        hombro_der: { x: 0.65, y: 0.3 },
        codo_izq: { x: 0.28, y: 0.45 },
        codo_der: { x: 0.72, y: 0.45 },
        muñeca_izq: { x: 0.25, y: 0.58 },
        muñeca_der: { x: 0.75, y: 0.58 },
        cadera_izq: { x: 0.4, y: 0.55 },
        cadera_der: { x: 0.6, y: 0.55 },
        rodilla_izq: { x: 0.38, y: 0.72 },
        rodilla_der: { x: 0.62, y: 0.72 },
        tobillo_izq: { x: 0.36, y: 0.88 },
        tobillo_der: { x: 0.64, y: 0.88 },
      },
    },
    {
      nombre: "Cadera bachata",
      descripcion: "Cadera desplazada a la derecha, peso en pie derecho",
      keypoints: {
        hombro_izq: { x: 0.33, y: 0.3 },
        hombro_der: { x: 0.63, y: 0.3 },
        codo_izq: { x: 0.26, y: 0.44 },
        codo_der: { x: 0.7, y: 0.44 },
        muñeca_izq: { x: 0.22, y: 0.57 },
        muñeca_der: { x: 0.74, y: 0.57 },
        cadera_izq: { x: 0.38, y: 0.56 },
        cadera_der: { x: 0.65, y: 0.54 },
        rodilla_izq: { x: 0.37, y: 0.73 },
        rodilla_der: { x: 0.63, y: 0.71 },
        tobillo_izq: { x: 0.35, y: 0.89 },
        tobillo_der: { x: 0.65, y: 0.87 },
      },
    },
  ],
  merengue: [
    {
      nombre: "Paso básico merengue",
      descripcion: "Marcha en el lugar, rodillas levantadas alternadas",
      keypoints: {
        hombro_izq: { x: 0.35, y: 0.28 },
        hombro_der: { x: 0.65, y: 0.28 },
        codo_izq: { x: 0.27, y: 0.42 },
        codo_der: { x: 0.73, y: 0.42 },
        muñeca_izq: { x: 0.3, y: 0.55 },
        muñeca_der: { x: 0.7, y: 0.55 },
        cadera_izq: { x: 0.4, y: 0.54 },
        cadera_der: { x: 0.6, y: 0.54 },
        rodilla_izq: { x: 0.4, y: 0.65 },
        rodilla_der: { x: 0.6, y: 0.75 },
        tobillo_izq: { x: 0.4, y: 0.82 },
        tobillo_der: { x: 0.6, y: 0.9 },
      },
    },
  ],
  salsa: [
    {
      nombre: "Paso básico salsa",
      descripcion: "Paso adelante-atrás, brazos en posición de pareja",
      keypoints: {
        hombro_izq: { x: 0.34, y: 0.29 },
        hombro_der: { x: 0.66, y: 0.29 },
        codo_izq: { x: 0.25, y: 0.4 },
        codo_der: { x: 0.68, y: 0.38 },
        muñeca_izq: { x: 0.2, y: 0.5 },
        muñeca_der: { x: 0.72, y: 0.45 },
        cadera_izq: { x: 0.39, y: 0.55 },
        cadera_der: { x: 0.61, y: 0.55 },
        rodilla_izq: { x: 0.37, y: 0.71 },
        rodilla_der: { x: 0.63, y: 0.71 },
        tobillo_izq: { x: 0.33, y: 0.88 },
        tobillo_der: { x: 0.63, y: 0.88 },
      },
    },
    {
      nombre: "Giro salsa",
      descripcion: "Preparación para giro, brazo derecho elevado",
      keypoints: {
        hombro_izq: { x: 0.36, y: 0.3 },
        hombro_der: { x: 0.64, y: 0.3 },
        codo_izq: { x: 0.3, y: 0.43 },
        codo_der: { x: 0.68, y: 0.2 },
        muñeca_izq: { x: 0.28, y: 0.55 },
        muñeca_der: { x: 0.7, y: 0.12 },
        cadera_izq: { x: 0.4, y: 0.55 },
        cadera_der: { x: 0.6, y: 0.55 },
        rodilla_izq: { x: 0.4, y: 0.72 },
        rodilla_der: { x: 0.6, y: 0.72 },
        tobillo_izq: { x: 0.38, y: 0.88 },
        tobillo_der: { x: 0.62, y: 0.88 },
      },
    },
  ],
  joropo: [
    {
      nombre: "Zapateo joropo",
      descripcion: "Postura erguida, brazos abiertos, peso en punta de pies",
      keypoints: {
        hombro_izq: { x: 0.32, y: 0.27 },
        hombro_der: { x: 0.68, y: 0.27 },
        codo_izq: { x: 0.22, y: 0.38 },
        codo_der: { x: 0.78, y: 0.38 },
        muñeca_izq: { x: 0.15, y: 0.48 },
        muñeca_der: { x: 0.85, y: 0.48 },
        cadera_izq: { x: 0.4, y: 0.54 },
        cadera_der: { x: 0.6, y: 0.54 },
        rodilla_izq: { x: 0.39, y: 0.7 },
        rodilla_der: { x: 0.61, y: 0.7 },
        tobillo_izq: { x: 0.38, y: 0.84 },
        tobillo_der: { x: 0.62, y: 0.84 },
      },
    },
  ],
  cumbia: [
    {
      nombre: "Paso básico cumbia",
      descripcion: "Paso lateral con falda, brazos extendidos suavemente",
      keypoints: {
        hombro_izq: { x: 0.34, y: 0.29 },
        hombro_der: { x: 0.66, y: 0.29 },
        codo_izq: { x: 0.26, y: 0.41 },
        codo_der: { x: 0.74, y: 0.41 },
        muñeca_izq: { x: 0.2, y: 0.52 },
        muñeca_der: { x: 0.8, y: 0.52 },
        cadera_izq: { x: 0.39, y: 0.55 },
        cadera_der: { x: 0.61, y: 0.55 },
        rodilla_izq: { x: 0.37, y: 0.72 },
        rodilla_der: { x: 0.63, y: 0.72 },
        tobillo_izq: { x: 0.34, y: 0.88 },
        tobillo_der: { x: 0.64, y: 0.88 },
      },
    },
  ],
  porro: [
    {
      nombre: "Paso básico porro",
      descripcion: "Movimiento circular de caderas, brazos relajados",
      keypoints: {
        hombro_izq: { x: 0.35, y: 0.3 },
        hombro_der: { x: 0.65, y: 0.3 },
        codo_izq: { x: 0.28, y: 0.44 },
        codo_der: { x: 0.72, y: 0.44 },
        muñeca_izq: { x: 0.3, y: 0.57 },
        muñeca_der: { x: 0.7, y: 0.57 },
        cadera_izq: { x: 0.38, y: 0.56 },
        cadera_der: { x: 0.62, y: 0.54 },
        rodilla_izq: { x: 0.37, y: 0.72 },
        rodilla_der: { x: 0.63, y: 0.72 },
        tobillo_izq: { x: 0.35, y: 0.88 },
        tobillo_der: { x: 0.63, y: 0.88 },
      },
    },
  ],
  tango: [
    {
      nombre: "Postura tango",
      descripcion: "Abrazo cerrado, espalda recta, cabeza hacia la izquierda",
      keypoints: {
        hombro_izq: { x: 0.33, y: 0.28 },
        hombro_der: { x: 0.63, y: 0.28 },
        codo_izq: { x: 0.24, y: 0.38 },
        codo_der: { x: 0.7, y: 0.35 },
        muñeca_izq: { x: 0.18, y: 0.46 },
        muñeca_der: { x: 0.74, y: 0.38 },
        cadera_izq: { x: 0.38, y: 0.55 },
        cadera_der: { x: 0.6, y: 0.55 },
        rodilla_izq: { x: 0.37, y: 0.72 },
        rodilla_der: { x: 0.61, y: 0.72 },
        tobillo_izq: { x: 0.35, y: 0.88 },
        tobillo_der: { x: 0.6, y: 0.88 },
      },
    },
    {
      nombre: "Caminata tango",
      descripcion: "Paso largo hacia adelante, peso en pie delantero",
      keypoints: {
        hombro_izq: { x: 0.34, y: 0.28 },
        hombro_der: { x: 0.64, y: 0.28 },
        codo_izq: { x: 0.25, y: 0.39 },
        codo_der: { x: 0.71, y: 0.36 },
        muñeca_izq: { x: 0.19, y: 0.47 },
        muñeca_der: { x: 0.75, y: 0.39 },
        cadera_izq: { x: 0.39, y: 0.55 },
        cadera_der: { x: 0.61, y: 0.55 },
        rodilla_izq: { x: 0.36, y: 0.68 },
        rodilla_der: { x: 0.62, y: 0.76 },
        tobillo_izq: { x: 0.32, y: 0.82 },
        tobillo_der: { x: 0.63, y: 0.9 },
      },
    },
  ],
};

export const ESTILOS_INFO: Record<
  EstiloBaile,
  { emoji: string; color: string; origen: string }
> = {
  bachata: { emoji: "💃", color: "from-red-500 to-pink-500", origen: "República Dominicana" },
  merengue: { emoji: "🎺", color: "from-yellow-500 to-orange-500", origen: "República Dominicana" },
  salsa: { emoji: "🔥", color: "from-orange-500 to-red-500", origen: "Colombia / Cuba" },
  joropo: { emoji: "🤠", color: "from-green-500 to-teal-500", origen: "Venezuela / Colombia" },
  cumbia: { emoji: "🥁", color: "from-yellow-400 to-yellow-600", origen: "Colombia" },
  porro: { emoji: "🎷", color: "from-purple-500 to-indigo-500", origen: "Colombia" },
  tango: { emoji: "🌹", color: "from-gray-700 to-gray-900", origen: "Argentina" },
};
